### ISSUE TITLE
kie-maven-plugin feature

### ISSUE THREAD

**Issue by kknd22** [kensiprell/grails3-drools-sample#1]
Does this plugin generate the pre-compiled rule binary like kie-maven-plugin does?

Moreover, does a gradle equivalent plugin like this exist? Thanks

**Comment by kensiprell** [comment]
Does this plugin generate the pre-compiled rule binary like kie-maven-plugin does? 
**No.**

Moreover, does a gradle equivalent plugin like this exist? 
**I started work on [one](https://github.com/kensiprell/grails3-drools), but I doubt I'll finish it.**
