### ISSUE TITLE
Having issue with Building this project

### ISSUE THREAD

**Issue by lakshmipmandava** [kensiprell/grails3-drools-sample#2]
Hi,
We are trying build this project and getting following issues

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'test-drools'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve org.grails.plugins:drools:0.1-SNAPSHOT.
     Required by:
         :test-drools:unspecified
      > Unable to load Maven meta-data from https://plugins.gradle.org/m2/org/grails/plugins/drools/0.1-SNAPSHOT/maven-metadata.xml.
         > Could not GET 'https://plugins.gradle.org/m2/org/grails/plugins/drools/0.1-SNAPSHOT/maven-metadata.xml'.
            > peer not authenticated

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

let us know, how to fix this issue.

thanks

**Comment by kensiprell** [comment]
Sorry, but I do not have time to provide support.
